apiVersion: v1
kind: Service
metadata:
  name: project1-service
spec:
  selector:
    app: project1
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
